export enum SeniorityLevel {
  Trainee_L1 = 1,
  Trainee_L2 = 2,
  Trainee_L3 = 3,
  Junior_L1 = 4,
  Junior_L2 = 5,
  Junior_L3 = 6,
  Advance_L1 = 7,
  Advance_L2 = 8,
  Advance_L3 = 9,
  Senior_L1 = 10,
  Senior_L2 = 11,
  Senior_L3 = 12,
  Master_L1 = 13,
  Master_L2 = 14,
  Master_L3 = 15,
}

export const SENIORITY_OPTIONS = [
  { value: "1", label: "Trainee L1" },
  { value: "2", label: "Trainee L2" },
  { value: "3", label: "Trainee L3" },
  { value: "4", label: "Junior L1" },
  { value: "5", label: "Junior L2" },
  { value: "6", label: "Junior L3" },
  { value: "7", label: "Advance L1" },
  { value: "8", label: "Advance L2" },
  { value: "9", label: "Advance L3" },
  { value: "10", label: "Senior L1" },
  { value: "11", label: "Senior L2" },
  { value: "12", label: "Senior L3" },
  { value: "13", label: "Master L1" },
  { value: "14", label: "Master L2" },
  { value: "15", label: "Master L3" },
];
